# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

# view_transitions: true
native_css_nesting: true
inline_css: true

sections: true
heading_ids: true

title_template: "%s //\\\\ Lel@Nekoweb.org"
author: Lel Illumina
favicon: /favicon.png
description: All Nekos are mine.
port: 8083

# OG image
origin: https://lel.nekoweb.org
theme_color: "#722014"

navigation:
  header:
    - Main: /
    - About: /about/
    - Blogs: /blogs/